DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    -- PK (user_id) will be generated by UUID
    user_id VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    is_confirmed BIT NOT NULL DEFAULT B'0',
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

DROP TABLE IF EXISTS schedules;
CREATE TABLE IF NOT EXISTS schedules (
    -- PK (schedule_id) will be generated by UUID
    schedule_id VARCHAR(100) UNIQUE NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    day INT NOT NULL CHECK(day >= 1 AND day <= 7 ),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT schedules_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT schedules_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
